# Generated by Django 4.0.4 on 2022-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_survey_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('IT', 'Italian'), ('ES', 'Spanish')], default='EN', max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Others')], default='EN', max_length=2)),
            ],
        ),
    ]
