# Generated by Django 4.0.4 on 2022-06-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_surveyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='survey_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='app.survey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Others')], default='X', max_length=1),
        ),
    ]
