# Generated by Django 4.0.4 on 2022-06-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_surveyuser_survey_id_alter_surveyuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
