# Generated by Django 4.0.4 on 2022-06-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_survey_external_description_survey_external_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=320, null=True)),
                ('max_segments', models.IntegerField(default=1)),
            ],
        ),
    ]
