# Generated by Django 4.0.4 on 2022-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_variablescategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='variables',
            field=models.JSONField(default=dict),
        ),
    ]
