# Generated by Django 4.0.4 on 2022-06-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_survey_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyuser',
            name='survey_id',
        ),
    ]
