# Generated by Django 4.0.4 on 2022-06-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_surveycase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveycase',
            old_name='survey_user_ud',
            new_name='survey_user_id',
        ),
    ]
