# Generated by Django 4.0.4 on 2022-06-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_survey_user_ud_surveycase_survey_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_zero',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VariableTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Template', max_length=32, null=True)),
                ('settings', models.TextField(blank=True, default=None, null=True)),
                ('segment', models.JSONField(default=dict)),
                ('text_internal', models.TextField(blank=True, default=None, null=True)),
                ('text_external', models.TextField(blank=True, default=None, null=True)),
                ('code_html', models.TextField(blank=True, default=None, null=True)),
                ('code_css', models.TextField(blank=True, default=None, null=True)),
                ('code_js', models.TextField(blank=True, default=None, null=True)),
                ('variable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.variablescategory')),
            ],
        ),
    ]
