# Generated by Django 4.0.4 on 2022-06-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_survey_survey_parent_survey_survey_zero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletemplates',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
