# Generated by Django 4.0.4 on 2022-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_variabletemplates_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletemplates',
            name='text_external',
            field=models.CharField(blank=True, default=None, max_length=3200, null=True),
        ),
        migrations.AlterField(
            model_name='variabletemplates',
            name='text_internal',
            field=models.CharField(blank=True, default=None, max_length=3200, null=True),
        ),
    ]
