# Generated by Django 4.0.4 on 2022-06-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_survey_external_faq_survey_external_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Form', max_length=32)),
                ('form_type', models.CharField(choices=[('T', 'Text'), ('R', 'Radio'), ('X', 'Others')], default='X', max_length=1)),
                ('django_form_name', models.CharField(default='TestForm()', max_length=32)),
            ],
        ),
    ]
