# Generated by Django 4.0.4 on 2022-06-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_formsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsurvey',
            name='form_text',
            field=models.TextField(blank=True, default='Please fill the form', null=True),
        ),
    ]
