# Generated by Django 4.0.4 on 2022-06-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_formsurvey_form_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsurvey',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('IT', 'Italian'), ('ES', 'Spanish')], default='EN', max_length=2),
        ),
    ]
