# Generated by Django 4.0.4 on 2022-06-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_formsurvey_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsurvey',
            old_name='form_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='formsurvey',
            old_name='form_type',
            new_name='type',
        ),
    ]
