# Generated by Django 4.0.4 on 2022-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_formsurvey_django_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsurvey',
            name='template_tag',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
