# Generated by Django 4.0.4 on 2022-06-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_formsurvey_template_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsurvey',
            name='template_tag',
            field=models.CharField(blank=True, default='formSubmit', max_length=32),
        ),
    ]
