# Generated by Django 4.0.4 on 2022-06-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_formsurvey_template_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsurvey',
            name='is_start',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
