# Generated by Django 4.0.4 on 2022-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_formsurvey_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='form_start',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='survey',
            name='forms_survey',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='formsurvey',
            name='django_form_name',
            field=models.CharField(choices=[('Radio5', 'Radio5'), ('Radio7', 'Radio7'), ('Text1', 'Text1'), ('NewSurveyUser', 'NewSurveyUser')], default='Text1', max_length=32),
        ),
    ]
