# Generated by Django 4.0.4 on 2022-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_formsurvey_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='forms_survey',
            new_name='form_survey',
        ),
        migrations.AlterField(
            model_name='formsurvey',
            name='template_tag',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
