# Generated by Django 4.0.4 on 2022-06-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_forms_survey_survey_form_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsurvey',
            name='django_form_name',
            field=models.CharField(choices=[('Radio5', 'Radio5'), ('Radio7', 'Radio7'), ('Text1', 'Text1'), ('NewSurveyUser', 'NewSurveyUser'), ('NewSurveyUserIT', 'NewSurveyUserIT')], default='Text1', max_length=32),
        ),
    ]
