# Generated by Django 4.0.4 on 2022-06-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_surveyuser_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='surveyuser',
            name='language',
        ),
    ]
