# Generated by Django 4.0.4 on 2022-06-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_survey_form_start_alter_survey_form_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='form_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_start', to='app.formsurvey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='form_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_survey', to='app.formsurvey'),
        ),
    ]
