# Generated by Django 4.0.4 on 2022-07-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_survey_form_start_alter_survey_form_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletemplates',
            name='zero_template',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
