# Generated by Django 4.0.4 on 2022-07-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_variabletemplates_zero_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variabletemplates',
            name='zero_template',
            field=models.BooleanField(default=False),
        ),
    ]
