# Generated by Django 4.0.4 on 2022-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_variabletemplates_zero_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsurvey',
            name='django_form_name',
            field=models.CharField(choices=[('Radio5', 'Radio5'), ('Radio7', 'Radio7'), ('Text1', 'Text1'), ('NewSurveyUser', 'NewSurveyUser'), ('NewSurveyUserIT', 'NewSurveyUserIT'), ('Radio50', 'Radio50')], default='Text1', max_length=32),
        ),
    ]
