# Generated by Django 4.0.4 on 2022-07-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_formsurvey_django_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsurvey',
            name='text_button',
            field=models.TextField(blank=True, default='Save', null=True),
        ),
    ]
