# Generated by Django 4.0.6 on 2022-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_formsurvey_text_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='first_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='last_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_end_text',
            field=models.CharField(default='Thanks.', max_length=720),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_case',
            field=models.CharField(default='Case', max_length=160),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_question',
            field=models.CharField(default='Questions', max_length=160),
        ),
    ]
