# Generated by Django 4.0.6 on 2022-08-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_parent',
            new_name='redirect_to',
        ),
    ]
