# Generated by Django 4.0.6 on 2022-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_survey_parent_survey_redirect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_end_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
