# Generated by Django 4.0.6 on 2022-08-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_survey_survey_end_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='first_survey',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_survey',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_zero',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
