# Generated by Django 4.0.6 on 2022-08-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_survey_first_survey_alter_survey_last_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='survey_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
