# Generated by Django 4.0.6 on 2022-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_surveyuser_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsurvey',
            name='django_form_name',
            field=models.CharField(choices=[('Radio5', 'Radio5'), ('Radio7', 'Radio7'), ('Text1', 'Text1'), ('NewSurveyUser', 'NewSurveyUser'), ('NewSurveyUserIT', 'NewSurveyUserIT'), ('Radio50', 'Radio50'), ('EmptyForm', 'EmptyForm')], default='Text1', max_length=32),
        ),
    ]
