# Generated by Django 4.0.6 on 2022-08-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_formsurvey_django_form_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='max_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
