# Generated by Django 4.0.6 on 2022-08-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_survey_max_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletemplates',
            name='language',
            field=models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('IT', 'Italian'), ('ES', 'Spanish')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='variabletemplates',
            name='segment_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
