# Generated by Django 4.0.6 on 2022-08-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_variabletemplates_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletemplates',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Others')], default='X', max_length=2),
        ),
    ]
