# Generated by Django 4.0.6 on 2022-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_variabletemplates_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuser',
            name='user_choiche',
            field=models.JSONField(default=dict),
        ),
    ]
