# Generated by Django 4.0.6 on 2022-08-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_surveyuser_user_choiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='suvery_var_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.variablescategory'),
        ),
    ]
