# Generated by Django 4.0.6 on 2022-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_survey_suvery_var_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.BooleanField(default=False)),
                ('tr', models.BooleanField(default=False)),
                ('se', models.BooleanField(default=False)),
                ('cm', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
