# Generated by Django 4.0.6 on 2022-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_countersurvey_cm_alter_countersurvey_co_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countersurvey',
            name='unique_id',
            field=models.IntegerField(default=0),
        ),
    ]
