# Generated by Django 4.0.6 on 2022-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_finalusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalusers',
            name='gend_f',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='gend_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='gend_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='lang_de',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='lang_en',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='lang_es',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='lang_it',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='lang_ot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
