# Generated by Django 4.0.6 on 2022-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_finalusers_gend_f_alter_finalusers_gend_m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSurveyZero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('case_id', models.IntegerField(blank=True, default=0, null=True)),
                ('variable_tested', models.IntegerField(blank=True, default=0, null=True)),
                ('template_id', models.IntegerField(blank=True, default=0, null=True)),
                ('answer_1', models.IntegerField(blank=True, default=0, null=True)),
                ('answer_2', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
