# Generated by Django 4.0.6 on 2022-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_formsurvey_django_form_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalusers',
            name='gend_f',
        ),
        migrations.RemoveField(
            model_name='finalusers',
            name='gend_x',
        ),
        migrations.RemoveField(
            model_name='finalusers',
            name='lang_en',
        ),
        migrations.RemoveField(
            model_name='finalusers',
            name='lang_es',
        ),
        migrations.RemoveField(
            model_name='finalusers',
            name='lang_it',
        ),
        migrations.RemoveField(
            model_name='finalusers',
            name='lang_ot',
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='gend_m',
            field=models.CharField(blank=True, default=0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='lang_de',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
