# Generated by Django 4.0.6 on 2022-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_finalusers_gend_f_remove_finalusers_gend_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalUserNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('lang_de', models.CharField(blank=True, default=0, max_length=2, null=True)),
                ('gend_m', models.CharField(blank=True, default=0, max_length=1, null=True)),
                ('age_range', models.IntegerField(blank=True, default=0, null=True)),
                ('occupation', models.IntegerField(blank=True, default=0, null=True)),
                ('academic', models.IntegerField(blank=True, default=0, null=True)),
                ('privacy', models.IntegerField(blank=True, default=0, null=True)),
                ('context', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='finalusers',
            name='gend_f',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finalusers',
            name='gend_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finalusers',
            name='lang_en',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finalusers',
            name='lang_es',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finalusers',
            name='lang_it',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finalusers',
            name='lang_ot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='gend_m',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalusers',
            name='lang_de',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
