# Generated by Django 4.0.6 on 2022-10-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_finalusernew_finalusers_gend_f_finalusers_gend_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalusernew',
            old_name='gend_m',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='finalusernew',
            old_name='lang_de',
            new_name='lang',
        ),
    ]
