# Generated by Django 4.0.6 on 2022-10-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_gend_m_finalusernew_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalusernew',
            name='click_ads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
