# Generated by Django 4.0.6 on 2022-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_finalusernew_click_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalsurveyzero',
            name='answer_2',
        ),
        migrations.AddField(
            model_name='finalsurveyzero',
            name='dep_var',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finalsurveyzero',
            name='gender',
            field=models.CharField(blank=True, default=0, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='finalsurveyzero',
            name='lang',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
