# Generated by Django 4.0.6 on 2023-01-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_finalsurveyzero_answer_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalsurvey',
            name='contextual_matching',
        ),
        migrations.RemoveField(
            model_name='finalsurvey',
            name='template_contextual_matching',
        ),
        migrations.AlterField(
            model_name='formsurvey',
            name='django_form_name',
            field=models.CharField(choices=[('Radio5', 'Radio5'), ('Radio5EN', 'Radio5EN'), ('Radio5ENCON', 'Radio5ENCON'), ('Radio5ITCON', 'Radio5ITCON'), ('Radio50EN', 'Radio50EN'), ('Radio7', 'Radio7'), ('Text1', 'Text1'), ('NewSurveyUserEN', 'NewSurveyUserEN'), ('NewSurveyUserIT', 'NewSurveyUserIT'), ('Radio50', 'Radio50'), ('EmptyForm', 'EmptyForm'), ('NewSurveyUserDE', 'NewSurveyUserDE'), ('Radio5DE', 'Radio5DE'), ('Radio5DECON', 'Radio5DECON'), ('Radio50DE', 'Radio50DE')], default='Text1', max_length=32),
        ),
    ]
