# Generated by Django 4.0.6 on 2023-01-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_countersurvey_cm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
