# Generated by Django 4.0.4 on 2022-05-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
